name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports: ['6379:6379']
        options: --entrypoint redis-server

    steps:
      - uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Run tests and linters
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/big_business_test
          REDIS_URL: redis://localhost:6379/0
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get update
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          sudo apt install -y postgresql-client || true
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rails db:prepare --trace
          bundle exec rake
